name: Build Image

on:
  workflow_call:
    inputs:
      name:
        description: "service name"
        required: false
        type: string
        default: ${{ github.repository }}
      ref:
        description: "git ref to checkout"
        required: false
        type: string
        default: ${{ github.sha }}
      build-args:
        description: "build args for image build"
        required: false
        type: string
        default: '{args: [COMMIT_HASH=abc,VERSION=1.27.0]}'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      # - name: Docker login
      #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # - uses: actions/github-script@v7
      #   id: script
      #   env:
      #     buildargs: ${{ inputs.build-args }}
      #   with:
      #     result-encoding: 'string'
      #     script: |
      #       const text = process.env.buildargs;
      #       const wordsArray = text.split(","); // Splitting by comma
      #       const multiLineString = wordsArray.join("\n"); // Joining with newlines
      #       console.log(multiLineString)

      - name: output result from script
        env:
          array: |-
            ${{ join(fromJSON(inputs.build-args).args, '
            ') }}
        run: |
          echo ${array}

      # - name: Build image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: false
      #     build-args: |
      #       ${{ steps.script.outputs.result }}
      #     tags: |
      #       ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.name }}:${{ steps.checkout.outputs.commit }}
