name: Build Image

on:
  workflow_call:
    inputs:
      name:
        description: "service name"
        required: false
        type: string
        default: ${{ github.repository }}
      ref:
        description: "git ref to checkout"
        required: false
        type: string
        default: ${{ github.sha }}
      build-args:
        description: "build args for image build"
        required: false
        type: string
        default: 'COMMIT_HASH=abc VERSION=1.27.0'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      # - name: Docker login
      #   run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: toJSON
        id: tojson
        run: |
          echo "out=${{ toJSON(inputs.build-args) }}" >> $GITHUB_OUTPUT
          echo "${{ toJSON(inputs.build-args) }}" >> $GITHUB_STEP_SUMMARY

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          build-args: ${{ inputs.build-args }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.name }}:${{ steps.checkout.outputs.commit }}
