name: Build Image

on:
  workflow_call:
    inputs:
      name:
        description: "service name"
        required: false
        type: string
        default: ${{ github.repository }}
      ref:
        description: "git ref to checkout"
        required: false
        type: string
        default: ${{ github.sha }}
      build-args:
        description: "build args for image build"
        required: false
        type: string
        default: ''
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Hash
        run: echo ${{ hashFiles('./foo.txt') }}

      - name: Sed
        id: sed
        run: |
          echo "result=$(echo ${{ inputs.build-args }} | sed -E 's/,/\n/')" >> $GITHUB_OUTPUT

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - uses: actions/github-script@v7
        id: script
        env:
          args: ${{ inputs.build-args }}
        with:
          result-encoding: 'string'
          script: |
            const text=process.env.args;
            const wordsArray = text.split(","); // Splitting by comma
            return wordsArray.join("\n");

      - name: Ensure service name
        id: repo
        run: echo "name=$(basename ${{ inputs.name }})" >> $GITHUB_OUTPUT

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          build-args: |-
            ${{ steps.sed.outputs.result }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo.outputs.name }}:${{ steps.checkout.outputs.commit }}
