name: CI

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      ref:
        required: false
        type: string
      build-args:
        required: false
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Output build args
        run: |
          echo ${{ inputs.build-args }}
          echo ${{ toJSON(inputs.build-args) }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            ${{ fromJSON(inputs.build-args) }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.name }}:${{ steps.checkout.outputs.commit }}
