name: Create Tag

on:
  workflow_call:
    inputs:
      service:
        description: "Name of the service which image we're tagging"
        required: true
        type: string
      environment:
        description: "The target environment(s) (e.g., staging, production)"
        required: true
        type: string
      version:
        description: "The version to deploy (e.g., semantic version or sequential number)"
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ${{ fromJSON(inputs.environment) }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Get service repo
        id: image-repo
        working-directory: helm
        run: echo "url=$(yq '.image.repository' values.yaml)" >> $GITHUB_OUTPUT

      - name: Retag image
        env:
          tag: ${{ matrix.environment }}-${{ inputs.version }}
        run: |
          docker pull ${{ steps.image-repo.outputs.url }}:${{ steps.checkout.outputs.commit }}
          docker tag ${{ steps.image-repo.outputs.url }}:${{ steps.checkout.outputs.commit }} ${{ steps.image-repo.outputs.url }}:${{ env.tag }}
          docker image push --all-tags ${{ steps.image-repo.outputs.url }}

      - name: Create and push Git tag
        env:
          tag: ${{ matrix.environment }}-${{ inputs.version }}
        run: |
          git config user.name "lneves75"
          git config user.email "luis.neves75@gmail.com"
          git tag -a "${{ env.tag }}" -m "Deployment to ${{ matrix.environment }}"
          git push origin "${{ env.tag }}"
